---
version: '3'
services:
  download-data:
    image: freqtradeorg/freqtrade:stable
    container_name: download-data
    volumes:
      - ".:/freqtrade/user_data/data"
    command: >
      download-data
      --timerange ${START_DATE:-20201201}-${END_DATE:-20211001}
      --timeframe 1m 5m 15m 1h 1d
      --datadir user_data/data/${EXCHANGE:-binance}
      --config user_data/data/pairlists.json
      --config user_data/data/config-${EXCHANGE:-binance}.json
      --config user_data/data/${EXCHANGE:-binance}-usdt-static.json
  
  kucoin-proxy:
    image: mikekonan/exchange-proxy:latest-arm64
    restart: unless-stopped
    command: -verbose 1
    container_name: kucoin-proxy

  binance-proxy:
    image: nightshift2k/binance-proxy
    restart: unless-stopped
    container_name: binance-proxy
